language: node_js

node_js:
  - 12.18.2

cache:
  bundler: true
  yarn: true
  directories:
      - node_modules

install:
  - yarn install
  - yarn add codecov -g

script:
  - yarn run test:unit
  - codecov
